<?php

use App\Http\Controllers\AuthentificationAdminController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\BusinessActivityController;
use App\Http\Controllers\BusinessController;
use App\Http\Controllers\BusinessTypeController;
use App\Http\Controllers\CampaignLocationController;
use App\Http\Controllers\CampaignPlacementController;
use App\Http\Controllers\LocationController;
use App\Http\Controllers\ParameterController;
use App\Http\Controllers\PlacementController;
use App\Http\Controllers\CampaignController;
use App\Http\Controllers\ScheduleController;
use App\Http\Controllers\trackingController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\AdvertiserController;
use App\Http\Controllers\ParametersController;
use App\Http\Controllers\Com_businessTypeController;
use App\Http\Controllers\Com_businessActivityController;
use Illuminate\Support\Facades\Route;

Route::post('/login', [LoginController::class, 'login']);
Route::apiResource('users', UserController::class, ['except' => ['destroy']]);
Route::apiResource('businesses', BusinessController::class, ['except' => ['destroy']]);
Route::apiResource('campaign', CampaignController::class);
Route::apiResource('locations', LocationController::class);
Route::get('/campaign_location', [CampaignLocationController::class, 'index']);
Route::post('/campaign_location', [CampaignLocationController::class, 'store']);
Route::get('/campaign_location/{campaign_id}/{location_id}', [CampaignLocationController::class, 'show']);
Route::put('/campaign_location/{campaign_id}/{location_id}', [CampaignLocationController::class, 'update']);
Route::delete('/campaign_location/{campaign_id}/{location_id}', [CampaignLocationController::class, 'destroy']);
Route::apiResource('advertiser',AdvertiserController::class);
Route::apiResource('tracking', trackingController::class);
Route::post('/track_campaign/{campaignId}', [trackingController::class,'trackCampaign']);
Route::post('login',[AuthentificationAdminController::class,'login']);
Route::put('/parameters/{parameters}',[ParametersController::class,'update']);
Route::get('/parameters/{parameters}', [ParametersController::class, 'show']);
Route::get('/parameters', [ParametersController::class, 'index']);
Route::apiResource('placements', PlacementController::class);
Route::apiResource('schedules', ScheduleController::class);
Route::apiResource('business_types', BusinessTypeController::class);
Route::apiResource('business_activities', BusinessActivityController::class);
Route::post('calculer',[CampaignController::class ,'calculateMinutes']);
Route::get('/campaign_locations', [CampaignLocationController::class, 'index']);
Route::post('/campaign_locations', [CampaignLocationController::class, 'store']);
Route::get('/campaign_locations/{campaign_id}/{location_id}', [CampaignLocationController::class, 'show']);
Route::put('/campaign_locations/{campaign_id}/{location_id}', [CampaignLocationController::class, 'update']);
Route::delete('/campaign_locations/{campaign_id}/{location_id}', [CampaignLocationController::class, 'destroy']);
Route::delete('schedules_business/{business_id}', [ScheduleController::class, 'delete'])->name('schedule.deleteAll');
Route::apiResource('parameter',ParameterController::class);
Route::apiResource('campaign_placements',CampaignPlacementController::class, ['except' => ['destroy','show', 'update']]);
Route::get('/campaign_placements/{campaign_id}/{placement_id}', [CampaignPlacementController::class, 'show']);
Route::put('/campaign_placements/{campaign_id}/{placement_id}', [CampaignPlacementController::class, 'update']);
Route::delete('/campaign_placements/{campaign_id}/{placement_id}', [CampaignPlacementController::class, 'destroy']);
Route::apiResource('campaign_businessType',Com_businessTypeController::class);
Route::apiResource('campaign_businessActivity',Com_businessActivityController::class);
Route::apiResource('tracking', TrackingController::class);
